In [1]:
import pandas as pd

In [2]:
# EDA explorarty data analysis
# load and understand structure
# clean data
# statistical summry
# visulation

In [3]:
info = {
    "Name"  :  ["Rajat","Rahul","Ruhi"],
    "GPA"   :  [7.8    ,9.78   ,8.7]
}

df = pd.DataFrame(info)
df

    Name   GPA
0  Rajat  7.80
1  Rahul  9.78
2   Ruhi  8.70

In [4]:
s = pd.Series([1,2,3,4,5,6,7])
# print(s)
# print(type(s))

# index
print(s[0])
print(s[6])

1
7

In [5]:
s = pd.Series([1,2,3,4], index=["Rajat","Ash","Ankita","Rihu"])
# s

print(s["Rajat"])
print(s["Ankita"])
print(s.iloc[0])
print(s.index)

1
3
1
Index(['Rajat', 'Ash', 'Ankita', 'Rihu'], dtype='object')

In [6]:
# Series Property

s1 = pd.Series([1,2,3,4,5,6])
s2 = pd.Series([7,8,9,10,11,12])

print(s1+s2)
s1[0] = 100
new_s1 = s1.drop(0)
print(s1)
print(new_s1)

0     8
1    10
2    12
3    14
4    16
5    18
dtype: int64
0    100
1      2
2      3
3      4
4      5
5      6
dtype: int64
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [7]:
# Data Frames (2D labeled array)
info = {
    "Name" : ["Rajat","Ruhi","Ankita"],
    "Age" : [19,21,20],
    "GPA" : [8.7,9.1,9.9]
}

df = pd.DataFrame(info)
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='object')

In [8]:
df = pd.DataFrame([["Ankita",20],["Rajat",19]],columns = ["Name","Age"])
df

     Name  Age
0  Ankita   20
1   Rajat   19

In [9]:
# Working with CSV and JSON files

# CSV data 
df = pd.read_csv("X:\\VScode\\Artificial_intelligence_n_Machine_learning\\Pandas\\employee_data (2).csv")
print(type(df),df)

<class 'pandas.core.frame.DataFrame'>    ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [10]:
# JSON file

df = pd.read_json("X:\\VScode\\Artificial_intelligence_n_Machine_learning\\Pandas\\employees.json")
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000