In [1]:
import pandas as pd
import numpy as np

In [20]:
data = {
    "Name": ["Aman", "Riya", "Ankita", "Neha"],
    "Age": [21, 22, 23, 24],
    "Marks": [50, 90, 99, 88]
}

df = pd.DataFrame(data)

In [10]:
df.head(2)

   Name  Age  Marks
0  Aman   21     85
1  Riya   22     90

In [17]:
df["Name"]

0      Aman
1      Riya
2    Ankita
3      Neha
Name: Name, dtype: object

In [23]:
df["Marks"] >= 80

0    False
1     True
2     True
3     True
Name: Marks, dtype: bool

In [26]:
df["Marks"].mean()

np.float64(81.75)

In [28]:
df.iloc[2]

Name     Ankita
Age          23
Marks        99
Name: 2, dtype: object

In [33]:
df["Result"] = df["Marks"] >= 80
df

     Name  Age  Marks  Result
0    Aman   21     50   False
1    Riya   22     90    True
2  Ankita   23     99    True
3    Neha   24     88    True

In [38]:
df = df.sort_values(by="Marks", ascending=False)
df

     Name  Age  Marks  Result
2  Ankita   23     99    True
1    Riya   22     90    True
3    Neha   24     88    True
0    Aman   21     50   False